name: Publish
on:
  push:
    tags:
    - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'grakhell/ExpandingLayout'
    steps:
      - name: Check
        uses: actions/checkout@v2
        with:
          repository: grakhell/ExpandingLayout
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Publish with Gradle
        uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: current
          arguments: publish --no-parallel -PsigningKey=${{secrets.GPG_KEY_CONTENTS}} -PsigningKeyId=${{secrets.SIGNING_KEYID}} -PsigningPassword=${{secrets.SIGNING_PASSWORD}} -PsonatypeUsername=${{secrets.SONATYPE_USERNAME}} -PsonatypePassword=${{secrets.SONATYPE_PASSWORD}} -PsonatypeProfileId=${{secrets.SONATYPE_PROFILE}} -PlibVersion=${GITHUB_REF:11}

