name: Build
on:
  push:
    branches:
    - master
    - dev
    - testing
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'grakhell/ExpandingLayout'
    steps:
    - name: Check
      uses: actions/checkout@v2
      with:
        repository: grakhell/ExpandingLayout
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v2
      with:
        gradle-version: current
        arguments: build --no-parallel -PsonatypeUsername=${{secrets.SONATYPE_USERNAME}} -PsonatypePassword=${{secrets.SONATYPE_PASSWORD}} -PsonatypeProfileId=${{secrets.SONATYPE_PROFILE}} -PlibVersion=${{secrets.BUILD_VERSION}} -PsigningKey=" " -PsigningKeyId=" " -PsigningPassword=" "
