name: Publish
on:
  push:
    tags:
    - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Prepare to publish
        run: |
           echo '${{secrets.GPG_KEY_CONTENTS}}' | base64 -d > publish_key.gpg
           gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.PASSPHRASE}}" \
           --output secret.gpg publish_key.gpg
           echo "::set-env name=LIB_VERSION::${GITHUB_REF:11}"
      - name: Publish with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: test publish -Psigning.secretKeyRingFile=secret.gpg -Psigning.gnupg.keyName=${{secrets.SIGNING_KEYID}} -Psigning.gnupg.passphrase=${{secrets.SIGNING_PASSWORD}} -PsonatypeUsername=${{secrets.SONATYPE_USERNAME}} -PsonatypePassword=${{secrets.SONATYPE_PASSWORD}} -PsonatypeProfileId=${{secrets.SONATYPE_PROFILE}}
